language: node_js
sudo: required
compiler:
  - gcc
  - clang
os:
  - linux
env:
  - CXX="g++-4.8" NODE_OPTIONS="--max-old-space-size=2048"
node_js:
  - '10.9'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn allchecks
