# TODO: Also release the built packages when pushing into `develop`
#
# yarn config set _authToken $NPM_AUTH_TOKEN &&
# yarn version --cwd package --non-interactive --no-git-tag-version --new-version=$(jq -r .version package.json)-dev.${TRAVIS_COMMIT::8} &&
# yarn publish --cwd package --non-interactive --tag=dev

name: Build & Test
on: [push]

jobs:
  name: Build & Test
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        # TODO: Consider caching this step
        run: yarn install --frozen-lockfile
      - name: Build contracts
        run: yarn build
      - name: Run test suite
        run: yarn test
      - name: Check types
        run: yarn typecheck
      - name: Check linting
        run: yarn lint
