name: Build & Test
on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          always-auth: true
          registry-url: https://npm.fury.io/melonproject/
          scope: '@melonproject'

      - name: Retrieve cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile contracts
        run: yarn compile

      - name: Run test suite
        run: yarn test
        env:
          MAINNET_ARCHIVE_NODE: ${{ secrets.MAINNET_ARCHIVE_NODE }}

      - name: Check types
        run: yarn typecheck

      - name: Check linting
        run: yarn lint

      - name: Publish development packages
        if: github.ref == 'refs/heads/develop'
        run: |
          yarn manypkg exec -- yarn version --non-interactive --no-git-tag-version --new-version=2.0.0-dev.$(git rev-list HEAD --count)+${GITHUB_SHA::8}
          yarn manypkg fix && yarn build
          yarn manypkg exec -- yarn publish --non-interactive --tag=dev --registry https://npm.fury.io/melonproject/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
