name: CI
on:
  push:
    branches:
      - v[1-9]*
      - audit/*
  pull_request:
    branches:
      - v[1-9]*
      - audit/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Display config
        run: forge config

      - name: Compile contracts
        run: make artifacts

      - name: Generate interfaces
        run: make interfaces

      - name: Run tests
        run: make test
        env:
          ETHEREUM_NODE_MAINNET: ${{ secrets.ETHEREUM_NODE_MAINNET }}
          ETHEREUM_NODE_POLYGON: ${{ secrets.ETHEREUM_NODE_POLYGON }}
          ETHEREUM_NODE_GOERLI: ${{ secrets.ETHEREUM_NODE_GOERLI }}

      - name: Check linting & formatting
        run: make lint
