name: CI
on:
  push:
    branches:
      - v[1-9]*
      - audit/*
  pull_request:
    branches:
      - v[1-9]*
      - audit/*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          [
            'persistent',
            'core',
            'infrastructure',
            'fee',
            'policy',
            'integration',
            'external',
            'peripheral',
            'utils',
            'e2e',
          ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - name: Hardhat artifact cache
        uses: actions/cache@v2
        with:
          path: |
            artifacts
            cache/solidity-files-cache.json
          key: ${{ runner.os }}-artifacts-3-${{ hashFiles('contracts/**/*.sol') }}
          restore-keys: |
            ${{ runner.os }}-artifacts-3-

      - name: Hardhat fork cache
        uses: actions/cache@v2
        with:
          path: cache/hardhat-network-fork
          key: fork-2-${{ matrix.project }}-${{ github.sha }}
          restore-keys: |
            fork-2-${{ matrix.project }}-
            fork-2-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile contracts
        run: yarn compile

      - name: Run tests
        run: yarn test --selectProjects ${{ matrix.project }}
        env:
          ETHEREUM_NODE_MAINNET: ${{ secrets.ETHEREUM_NODE_MAINNET }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - name: Hardhat artifact cache
        uses: actions/cache@v2
        with:
          path: |
            artifacts
            cache/solidity-files-cache.json
          key: ${{ runner.os }}-artifacts-3-${{ hashFiles('contracts/**/*.sol') }}
          restore-keys: |
            ${{ runner.os }}-artifacts-3-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Compile contracts
        run: yarn compile

      - name: Check types
        run: yarn typecheck

      - name: Check linting
        run: yarn lint
