name: Publish

on:
  push:
    branches:
      - next

jobs:
  publish:
    if: github.repository == 'avantgardefinance/protocol'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Hardhat artifact cache
        uses: actions/cache@v2
        with:
          path: |
            artifacts
            cache/solidity-files-cache.json
          key: ${{ runner.os }}-artifacts-${{ hashFiles('contracts/**/*.sol') }}
          restore-keys: |
            ${{ runner.os }}-artifacts-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create release pull request or publish
        id: changesets
        uses: changesets/action@master
        with:
          publish: yarn release
          title: 'chore: publish private packages'
          commit: 'chore: publish private packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
